[package]
name = "serea-capability"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
serea-protocol.workspace = true
serea-storage.workspace = true
serea-event-bus.workspace = true

[dev-dependencies]
serea-testkit.workspace = true
serea-storage = { workspace = true, features = ["p2h-fault-injection"] }
